apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gfur5vrrl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gfur5vrrl-python 
  name: gfur5vrrl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gfur5vrrl-python 
